default_platform(:ios)

platform :ios do

  desc "Push a new test build to TestFlight"
  lane :beta do
    update_project_team(
      path: "ios.xcodeproj",
      teamid: "6S4L29QT59"
    )
    update_app_identifier(
      xcodeproj: "ios.xcodeproj",
      plist_path: "ios/Info.plist",
      app_identifier: "app.livetl.ios"
    )
    update_app_identifier(
      xcodeproj: "ios.xcodeproj",
      plist_path: "yt-extension/Info.plist",
      app_identifier: "app.livetl.ios.yt-extension"
    )

    increment_build_number(
      xcodeproj: "ios.xcodeproj",
      build_number: latest_testflight_build_number + 1
    )

    build_app(
      workspace: "ios.xcworkspace",
      scheme: "ios",
    )

    upload_to_testflight
  end

  desc "Push a new release build to the App Store"
  lane :release do
    update_project_team(
      path: "ios.xcodeproj",
      teamid: "6S4L29QT59"
    )
    update_app_identifier(
      xcodeproj: "ios.xcodeproj",
      plist_path: "ios/Info.plist",
      app_identifier: "app.livetl.ios"
    )
    update_app_identifier(
      xcodeproj: "ios.xcodeproj",
      plist_path: "yt-extension/Info.plist",
      app_identifier: "app.livetl.ios.yt-extension"
    )

    increment_build_number(
      xcodeproj: "ios.xcodeproj",
      build_number: latest_testflight_build_number + 1
    )

    build_app(
      workspace: "ios.xcworkspace",
      scheme: "ios",
    )

    upload_to_testflight
  end
end
