default_platform(:ios)

platform :ios do

  desc "Push a new release build to the App Store"
  lane :release do
    match(readonly: true)
    sigh
    increment_build_number(xcodeproj: "ios.xcodeproj")
    build_app(workspace: "ios.xcworkspace", scheme: "ios")
    upload_to_testflight
  end
end
