default_platform(:ios)

platform :ios do

  desc "Push a new release build to the App Store"
  lane :release do
    match
    increment_build_number(xcodeproj: "ios.xcodeproj")
    build_app(workspace: "ios.xcworkspace", scheme: "ios")
    upload_to_app_store(skip_submission: true)
  end
end
